//! Scalar-vs-SIMD measurements for the log-parsing hot path.
//!
//! # What this measures and why
//!
//! A callgrind profile of the end-to-end parse attributes ~28% of instructions
//! to `regex_automata`'s bounded backtracker — the engine the `regex` crate
//! falls back to for *capture extraction* on short haystacks — and ~14% to
//! malloc/free. The patterns responsible all describe fixed byte shapes
//! (a timestamp, a `(cost=..)` tuple, a leading-whitespace run, a set of
//! literal node-type names), which is exactly the work byte-parallel compares
//! do well.
//!
//! Each group below measures **three tiers** on the same input:
//!
//! * `current` — what the parser does today (regex, or `char`-by-`char`).
//! * `scalar`  — the same job as a plain byte loop, no regex, no allocation.
//! * `simd`    — the byte loop vectorised (SSE2/AVX2, runtime-detected).
//!
//! Reporting all three is the point. Replacing a regex with a byte scanner
//! bundles two separate wins — *not running a regex engine* and *comparing 16
//! or 32 bytes at once* — and only the second is attributable to SIMD. The
//! `scalar` tier is what separates them; without it a "20x SIMD speedup" claim
//! would mostly be measuring the regex removal.
//!
//! # Input realism
//!
//! The corpus is generated by the same auto_explain log generator used by
//! `benches/log_parsing.rs` and `benches/grouping.rs` (itself modeled on the
//! fixtures in the `log_parser` unit tests): ~89% tab-indented continuation
//! lines, ~2.3 KB per plan, long `Filter:` lines, and interleaved unrelated
//! server log lines. Crucially, each scanner is measured over the line mix it
//! would really see — the timestamp split over *every* line including the
//! continuations it must reject, not just over timestamps it can match.
//!
//! Every fast path is checked against its current implementation over the
//! whole corpus before timing starts, so the numbers cannot come from a
//! scanner that silently does less work.

use criterion::{Criterion, Throughput, criterion_group, criterion_main};
use pg_plansight_core::log_parser::PostgreSQLLogParser;
use pg_plansight_core::parser_utils::{RegexPatterns, get_indent_level, split_log_line};
use pg_plansight_core::simd_scan::{
    Verdict, find_ascii_ci_scalar, find_ascii_ci_simd, find_literal_scalar, find_literal_simd,
    leading_whitespace_scalar, leading_whitespace_simd, timestamp_prefix_len_scalar,
    timestamp_prefix_len_simd,
};
use regex::Regex;
use std::fmt::Write as _;
use std::hint::black_box;
use std::time::Duration;

// ---------------------------------------------------------------------------
// Corpus: the same generator shape as the other core benches.
// ---------------------------------------------------------------------------

fn format_ts(ms: u64) -> String {
    let day = 12 + ms / 86_400_000;
    let rem = ms % 86_400_000;
    format!(
        "2025-06-{:02} {:02}:{:02}:{:02}.{:03}",
        day,
        rem / 3_600_000,
        (rem / 60_000) % 60,
        (rem / 1000) % 60,
        rem % 1000
    )
}

fn push_plan(out: &mut String, i: usize, shape: usize, ts_ms: u64, table: &str) {
    let pid = 3_416_000 + i % 800;
    let duration = 10.0 + ((i % 997) as f64) * 1.37;
    writeln!(
        out,
        "{} UTC [{pid}] LOG:  duration: {duration:.3} ms  plan:",
        format_ts(ts_ms)
    )
    .unwrap();
    writeln!(
        out,
        "\tQuery Text: SELECT t.\"Id\", t.\"Status\", t.\"CreatedAt\", t.\"Payload\", t.\"OwnerId\""
    )
    .unwrap();
    writeln!(out, "\tFROM \"public\".\"{table}\" AS t").unwrap();
    writeln!(
        out,
        "\tWHERE t.\"Status\" = $1 AND t.\"CreatedAt\" >= $2 AND t.\"OwnerId\" IN ($3, $4)"
    )
    .unwrap();
    if shape.is_multiple_of(2) {
        writeln!(out, "\tORDER BY t.\"CreatedAt\" DESC").unwrap();
    }
    if shape % 4 < 3 {
        writeln!(out, "\tLIMIT $5").unwrap();
    }
    writeln!(out, "\tLimit  (cost=0.43..599.04 rows=1000 width=56)").unwrap();
    writeln!(
        out,
        "\t  Output: \"Id\", \"Status\", \"CreatedAt\", \"Payload\", \"OwnerId\""
    )
    .unwrap();
    writeln!(
        out,
        "\t  ->  Index Scan Backward using \"IX_{table}_CreatedAt\" on \"public\".\"{table}\" t  (cost=0.43..95610.13 rows=159718 width=56)"
    )
    .unwrap();
    writeln!(
        out,
        "\t        Output: \"Id\", \"Status\", \"CreatedAt\", \"Payload\", \"OwnerId\""
    )
    .unwrap();
    writeln!(out, "\t        Index Cond: (t.\"CreatedAt\" IS NOT NULL)").unwrap();
    writeln!(
        out,
        "\t        Filter: ((NOT t.\"Deleted\") AND (((t.\"Level\" > '66'::double precision) AND (t.\"Level\" <= '99'::double precision) AND (t.\"CreatedAt\" <= '2025-06-11 23:00:15.671506+00'::timestamp with time zone)) OR ((t.\"Level\" <= '66'::double precision) AND (t.\"CreatedAt\" <= '2025-06-11 23:30:15.671506+00'::timestamp with time zone))) AND (t.\"Status\" = ANY ('{{1,2,3,4}}'::integer[])))"
    )
    .unwrap();
    for j in 0..(4 + i % 9) {
        writeln!(
            out,
            "\t        ->  Bitmap Heap Scan on \"public\".\"{table}_c{j}\" c{j}  (cost=12.15..870.{j:02} rows={} width=24)",
            100 + j * 7
        )
        .unwrap();
    }
    writeln!(
        out,
        "{} UTC [{}] LOG:  checkpoint complete: wrote {} buffers (0.4%); sync files={}",
        format_ts(ts_ms + 3),
        pid + 1,
        100 + i % 500,
        i % 32
    )
    .unwrap();
}

fn realistic_log(num_plans: usize) -> String {
    let mut out = String::with_capacity(num_plans * 2400);
    for i in 0..num_plans {
        let shape = i % 20;
        let table = format!("tbl_{shape}");
        push_plan(&mut out, i, shape, (i as u64) * 47, &table);
    }
    out
}

/// The line slices each scanner is measured over.
struct Corpus {
    /// Every line, in file order — the mix the read loop really sees.
    all: Vec<String>,
    /// Only the timestamped lines (~11% of `all`).
    timestamped: Vec<String>,
    /// Continuation lines with leading indentation stripped of the leading
    /// tab, as `PlanLine::new` receives them.
    plan_lines: Vec<String>,
    /// Only lines carrying a `(cost=..)` tuple — the node lines.
    node_lines: Vec<String>,
}

fn corpus(num_plans: usize) -> Corpus {
    let content = realistic_log(num_plans);
    let all: Vec<String> = content.lines().map(str::to_string).collect();
    let timestamped: Vec<String> = all
        .iter()
        .filter(|l| l.as_bytes().first().is_some_and(u8::is_ascii_digit))
        .cloned()
        .collect();
    let plan_lines: Vec<String> = all
        .iter()
        .filter(|l| l.starts_with('\t'))
        .map(|l| l.trim_start_matches('\t').to_string())
        .collect();
    let node_lines: Vec<String> = plan_lines
        .iter()
        .filter(|l| l.contains("(cost="))
        .cloned()
        .collect();
    Corpus {
        all,
        timestamped,
        plan_lines,
        node_lines,
    }
}

fn total_bytes(lines: &[String]) -> u64 {
    lines.iter().map(|l| l.len() as u64).sum()
}

// ---------------------------------------------------------------------------
// 1. Timestamp split — `split_log_line` / LOG_LINE_PATTERN group 1.
// ---------------------------------------------------------------------------

/// Byte-scanner drop-in for [`split_log_line`], deferring to the regex only
/// when the fast path reports [`Verdict::Unsure`]. This is the shape a real
/// integration would take, so it is what gets measured — including the
/// fallback branch.
#[inline]
fn split_scanned<'a>(
    line: &'a str,
    fallback: &Regex,
    scan: fn(&[u8]) -> Verdict,
) -> Option<(&'a str, &'a str)> {
    match scan(line.as_bytes()) {
        Verdict::Match(n) => Some((&line[..n], &line[n..])),
        Verdict::NoMatch => None,
        Verdict::Unsure => {
            let caps = fallback.captures(line)?;
            Some((caps.get(1)?.as_str(), caps.get(2)?.as_str()))
        }
    }
}

/// The pre-integration `split_log_line`, kept verbatim here.
///
/// The library version now answers from the byte scanner, so calling it would
/// make this group measure the scanner against itself. Holding the old
/// implementation locally keeps `current_regex` meaningful as the baseline it
/// is labelled as.
#[inline]
fn split_legacy_regex<'a>(line: &'a str, fallback: &Regex) -> Option<(&'a str, &'a str)> {
    let first = *line.as_bytes().first()?;
    if first.is_ascii() && !first.is_ascii_digit() {
        return None;
    }
    let caps = fallback.captures(line)?;
    Some((caps.get(1)?.as_str(), caps.get(2)?.as_str()))
}

/// The pre-integration `get_indent_level`, kept for the same reason.
#[inline]
fn indent_legacy_chars(line: &str) -> usize {
    line.chars().take_while(|c| c.is_whitespace()).count()
}

fn bench_timestamp_split(c: &mut Criterion) {
    let corpus = corpus(400);
    // The exact regex the parser uses, rather than a copy of the pattern.
    let re = RegexPatterns::default().log_line_regex;

    // Equivalence gate: both scanners must agree with the production splitter
    // on every line of the corpus before any timing is reported.
    for line in &corpus.all {
        let want = split_legacy_regex(line, &re);
        // The shipped `split_log_line` is now the integrated scanner; assert it
        // still agrees with the regex it replaced.
        assert_eq!(
            split_log_line(line, &re),
            want,
            "shipped split disagrees on {line:?}"
        );
        assert_eq!(
            split_scanned(line, &re, timestamp_prefix_len_scalar),
            want,
            "scalar timestamp split disagrees on {line:?}"
        );
        assert_eq!(
            split_scanned(line, &re, timestamp_prefix_len_simd),
            want,
            "simd timestamp split disagrees on {line:?}"
        );
    }

    // Two views: the realistic mix (where the existing tab fast-reject already
    // skips ~89% of lines) and timestamped lines only (where the regex
    // actually runs). The first is the honest end-to-end figure; the second
    // isolates the win on the lines that pay for it.
    for (name, lines) in [
        ("realistic_mix", &corpus.all),
        ("timestamped_only", &corpus.timestamped),
    ] {
        let mut group = c.benchmark_group(format!("timestamp_split/{name}"));
        group.throughput(Throughput::Elements(lines.len() as u64));

        group.bench_function("current_regex", |b| {
            b.iter(|| {
                for line in lines.iter() {
                    black_box(split_legacy_regex(black_box(line), &re));
                }
            });
        });
        group.bench_function("scalar", |b| {
            b.iter(|| {
                for line in lines.iter() {
                    black_box(split_scanned(
                        black_box(line),
                        &re,
                        timestamp_prefix_len_scalar,
                    ));
                }
            });
        });
        // Measures the shipped `split_log_line`, i.e. the integrated path.
        group.bench_function("simd", |b| {
            b.iter(|| {
                for line in lines.iter() {
                    black_box(split_log_line(black_box(line), &re));
                }
            });
        });
        group.finish();
    }
}

// ---------------------------------------------------------------------------
// 2. Indentation — `get_indent_level`, called once per plan line.
// ---------------------------------------------------------------------------

fn bench_indent_level(c: &mut Criterion) {
    let corpus = corpus(400);
    let lines = &corpus.plan_lines;

    for line in lines {
        let want = indent_legacy_chars(line);
        assert_eq!(
            get_indent_level(line),
            want,
            "shipped indent disagrees on {line:?}"
        );
        for (name, got) in [
            ("scalar", leading_whitespace_scalar(line.as_bytes())),
            ("simd", leading_whitespace_simd(line.as_bytes())),
        ] {
            match got {
                Verdict::Match(n) => assert_eq!(n, want, "{name} indent disagrees on {line:?}"),
                _ => panic!("{name} declined an all-ASCII line: {line:?}"),
            }
        }
    }

    let mut group = c.benchmark_group("indent_level");
    group.throughput(Throughput::Elements(lines.len() as u64));

    group.bench_function("current_chars", |b| {
        b.iter(|| {
            for line in lines.iter() {
                black_box(indent_legacy_chars(black_box(line)));
            }
        });
    });
    group.bench_function("scalar", |b| {
        b.iter(|| {
            for line in lines.iter() {
                black_box(leading_whitespace_scalar(black_box(line).as_bytes()));
            }
        });
    });
    // Measures the shipped `get_indent_level`, i.e. the integrated path.
    group.bench_function("simd", |b| {
        b.iter(|| {
            for line in lines.iter() {
                black_box(get_indent_level(black_box(line)));
            }
        });
    });
    group.finish();
}

// ---------------------------------------------------------------------------
// 3. Plan-node detection — is this line a node line (`(cost=..)`)?
// ---------------------------------------------------------------------------

fn bench_node_detection(c: &mut Criterion) {
    let corpus = corpus(400);
    let lines = &corpus.plan_lines;
    // The pattern `RegexPatterns::plan_regex` / `PLAN_NODE_REGEX` use.
    let plan_re = Regex::new(r"\(cost=[\d.]+\.\.[\d.]+\s+rows=\d+\s+width=\d+\)").unwrap();

    // The literal prefilter is only a *screen*: it says "no `(cost=` here, so
    // the regex cannot match". Where the literal is present the regex still
    // has to run, so the gate below asserts the screen never produces a false
    // negative rather than asserting full equivalence.
    for line in lines {
        let has_literal = find_literal_simd(line.as_bytes(), b"(cost=").is_some();
        assert_eq!(
            has_literal,
            find_literal_scalar(line.as_bytes(), b"(cost=").is_some(),
            "literal scanners disagree on {line:?}"
        );
        if plan_re.is_match(line) {
            assert!(
                has_literal,
                "screen would reject a real node line: {line:?}"
            );
        }
    }

    let mut group = c.benchmark_group("node_detection");
    group.throughput(Throughput::Elements(lines.len() as u64));

    group.bench_function("current_regex", |b| {
        b.iter(|| {
            for line in lines.iter() {
                black_box(plan_re.is_match(black_box(line)));
            }
        });
    });
    // Screen first, regex only on lines that survive it — the integration a
    // real change would make, since the regex still validates the shape.
    group.bench_function("scalar_screen_then_regex", |b| {
        b.iter(|| {
            for line in lines.iter() {
                let line = black_box(line);
                let hit = find_literal_scalar(line.as_bytes(), b"(cost=").is_some()
                    && plan_re.is_match(line);
                black_box(hit);
            }
        });
    });
    group.bench_function("simd_screen_then_regex", |b| {
        b.iter(|| {
            for line in lines.iter() {
                let line = black_box(line);
                let hit = find_literal_simd(line.as_bytes(), b"(cost=").is_some()
                    && plan_re.is_match(line);
                black_box(hit);
            }
        });
    });
    // Control: the same screen using `memchr`'s `memmem`, the best-in-class
    // SIMD substring searcher. If this loses too, the screen itself is the
    // wrong idea rather than the hand-written scanner being slow.
    let finder = memchr::memmem::Finder::new(b"(cost=");
    group.bench_function("memmem_screen_then_regex", |b| {
        b.iter(|| {
            for line in lines.iter() {
                let line = black_box(line);
                let hit = finder.find(line.as_bytes()).is_some() && plan_re.is_match(line);
                black_box(hit);
            }
        });
    });
    group.finish();
}

// ---------------------------------------------------------------------------
// 4. Node-type classification — the `to_lowercase()` + `contains()` chain.
// ---------------------------------------------------------------------------

/// The needles `ScanType::analyze` and its siblings test, in order. The
/// current code allocates one lowercased `String` per line and then walks this
/// list with `contains()`.
const NODE_NEEDLES: [&str; 8] = [
    "bitmap index scan",
    "parallel bitmap heap scan",
    "bitmap heap scan",
    "seq scan",
    "nested loop",
    "hash join",
    "merge join",
    "aggregate",
];

/// Reproduces the current chain: one Unicode-aware lowercase allocation, then
/// a linear scan of the needles.
#[inline]
fn classify_current(line: &str) -> Option<usize> {
    let lowered = line.to_lowercase();
    NODE_NEEDLES.iter().position(|n| lowered.contains(n))
}

#[inline]
fn classify_scanned(line: &str, scan: fn(&[u8], &[u8]) -> Verdict) -> Option<usize> {
    for (i, needle) in NODE_NEEDLES.iter().enumerate() {
        match scan(line.as_bytes(), needle.as_bytes()) {
            Verdict::Match(_) => return Some(i),
            Verdict::NoMatch => {}
            // Non-ASCII identifiers: fall back to the exact Unicode path.
            Verdict::Unsure => return classify_current(line),
        }
    }
    None
}

/// Single-pass multi-pattern alternative: `aho-corasick` compiles all eight
/// needles into one automaton and, for a set this small with short literals,
/// selects its SIMD "Teddy" prefilter — so the line is scanned once with
/// vector compares instead of once per needle.
///
/// `position()` on the needle list gives priority by *list order*, not by
/// position in the line, so the leftmost-first match kind would not be
/// equivalent. Overlapping iteration reporting the minimum pattern id is;
/// finding id 0 allows an early exit since nothing can outrank it.
#[inline]
fn classify_aho(line: &str, ac: &aho_corasick::AhoCorasick) -> Option<usize> {
    if !line.is_ascii() {
        return classify_current(line);
    }
    let mut best: Option<usize> = None;
    for m in ac.find_overlapping_iter(line) {
        let id = m.pattern().as_usize();
        if id == 0 {
            return Some(0);
        }
        best = Some(best.map_or(id, |b: usize| b.min(id)));
    }
    best
}

fn bench_node_classification(c: &mut Criterion) {
    let corpus = corpus(400);
    let lines = &corpus.node_lines;

    let ac = aho_corasick::AhoCorasick::builder()
        .ascii_case_insensitive(true)
        .build(NODE_NEEDLES)
        .unwrap();

    for line in lines {
        let want = classify_current(line);
        assert_eq!(
            classify_scanned(line, find_ascii_ci_scalar),
            want,
            "scalar classification disagrees on {line:?}"
        );
        assert_eq!(
            classify_scanned(line, find_ascii_ci_simd),
            want,
            "simd classification disagrees on {line:?}"
        );
        assert_eq!(
            classify_aho(line, &ac),
            want,
            "aho-corasick classification disagrees on {line:?}"
        );
    }

    let mut group = c.benchmark_group("node_classification");
    group.throughput(Throughput::Elements(lines.len() as u64));

    group.bench_function("current_to_lowercase", |b| {
        b.iter(|| {
            for line in lines.iter() {
                black_box(classify_current(black_box(line)));
            }
        });
    });
    group.bench_function("scalar_ascii_ci", |b| {
        b.iter(|| {
            for line in lines.iter() {
                black_box(classify_scanned(black_box(line), find_ascii_ci_scalar));
            }
        });
    });
    group.bench_function("simd_ascii_ci", |b| {
        b.iter(|| {
            for line in lines.iter() {
                black_box(classify_scanned(black_box(line), find_ascii_ci_simd));
            }
        });
    });
    group.bench_function("simd_aho_corasick", |b| {
        b.iter(|| {
            for line in lines.iter() {
                black_box(classify_aho(black_box(line), &ac));
            }
        });
    });
    group.finish();
}

// ---------------------------------------------------------------------------
// 5. Cost tuple extraction — `COST_REGEX.captures()` in `extract_cost`.
// ---------------------------------------------------------------------------

/// `(cost=1.23..4.56 rows=7 width=8)` as (startup, total, rows, width).
type CostTuple = (f64, f64, u64, u32);

/// Byte-wise equivalent of `PlanParser::extract_cost`, parameterised by how
/// the `(cost=` marker is located so the SIMD contribution is isolated from
/// the field parsing (which stays scalar in both tiers).
#[inline]
fn extract_cost_scanned(line: &str, find: fn(&[u8], &[u8]) -> Option<usize>) -> Option<CostTuple> {
    let b = line.as_bytes();
    let start = find(b, b"(cost=")? + b"(cost=".len();

    // Each field is a run of digits and dots ended by a known delimiter.
    fn num(b: &[u8], mut i: usize) -> (usize, usize) {
        let s = i;
        while i < b.len() && (b[i].is_ascii_digit() || b[i] == b'.') {
            i += 1;
        }
        (s, i)
    }
    // `min` runs up to the `..` separator, so stop at the first dot that is
    // followed by another dot rather than at any dot.
    let mut i = start;
    while i < b.len() && (b[i].is_ascii_digit() || (b[i] == b'.' && b.get(i + 1) != Some(&b'.'))) {
        i += 1;
    }
    let min = std::str::from_utf8(&b[start..i])
        .ok()?
        .parse::<f64>()
        .ok()?;
    if b.get(i) != Some(&b'.') || b.get(i + 1) != Some(&b'.') {
        return None;
    }
    let (s, e) = num(b, i + 2);
    let max = std::str::from_utf8(&b[s..e]).ok()?.parse::<f64>().ok()?;

    let rest = &b[e..];
    let r = find(rest, b"rows=")? + b"rows=".len();
    let (s, e2) = num(rest, r);
    let rows = std::str::from_utf8(&rest[s..e2])
        .ok()?
        .parse::<u64>()
        .ok()?;

    let rest2 = &rest[e2..];
    let w = find(rest2, b"width=")? + b"width=".len();
    let (s, e3) = num(rest2, w);
    let width = std::str::from_utf8(&rest2[s..e3])
        .ok()?
        .parse::<u32>()
        .ok()?;

    Some((min, max, rows, width))
}

fn bench_cost_extraction(c: &mut Criterion) {
    let corpus = corpus(400);
    let lines = &corpus.node_lines;
    let cost_re = Regex::new(
        r"\(cost=(?<min>[\d.]+)\.\.(?<max>[\d.]+)\s+rows=(?<rows>\d+)\s+width=(?<width>\d+)\)",
    )
    .unwrap();

    let via_regex = |line: &str| -> Option<CostTuple> {
        let c = cost_re.captures(line)?;
        Some((
            c["min"].parse().ok()?,
            c["max"].parse().ok()?,
            c["rows"].parse().ok()?,
            c["width"].parse().ok()?,
        ))
    };

    for line in lines {
        let want = via_regex(line);
        assert_eq!(
            extract_cost_scanned(line, find_literal_scalar),
            want,
            "scalar cost extraction disagrees on {line:?}"
        );
        assert_eq!(
            extract_cost_scanned(line, find_literal_simd),
            want,
            "simd cost extraction disagrees on {line:?}"
        );
    }

    let mut group = c.benchmark_group("cost_extraction");
    group.throughput(Throughput::Elements(lines.len() as u64));

    group.bench_function("current_regex", |b| {
        b.iter(|| {
            for line in lines.iter() {
                black_box(via_regex(black_box(line)));
            }
        });
    });
    group.bench_function("scalar", |b| {
        b.iter(|| {
            for line in lines.iter() {
                black_box(extract_cost_scanned(black_box(line), find_literal_scalar));
            }
        });
    });
    group.bench_function("simd", |b| {
        b.iter(|| {
            for line in lines.iter() {
                black_box(extract_cost_scanned(black_box(line), find_literal_simd));
            }
        });
    });
    group.finish();
}

// ---------------------------------------------------------------------------
// 6. Composite: the per-line work of the read loop, current vs. optimised.
// ---------------------------------------------------------------------------

/// The per-site groups above each isolate one primitive, which makes them easy
/// to reason about but leaves the aggregate to guesswork — you would have to
/// multiply each delta by a call count you have not measured. This group
/// replays the three winning sites at the call counts the parser *actually*
/// performs, so the aggregate is measured rather than projected.
///
/// The counts come from instrumenting `PostgreSQLLogParser` with atomic
/// counters and parsing a 2,000-plan log of exactly this shape:
///
/// ```text
/// split_log_line   36,993   (once per line; only 4,000 reach the regex,
///                            the rest are rejected by the leading-tab test)
/// get_indent_level 51,986   (~1.6x per continuation line — plan text is
///                            walked more than once during finalisation)
/// extract_cost     19,993   (once per node line)
/// COST_REGEX::is_match  0   (`parse_lines` is not on this path at all)
/// ```
///
/// Two consequences worth stating plainly. Node detection is excluded because
/// it never runs — and the `node_detection` group showed a literal screen
/// loses there anyway, since `regex` already applies a SIMD prefilter of its
/// own. And indentation is replayed once per continuation line rather than
/// 1.6x, which *understates* that site's contribution; the aggregate below is
/// therefore a conservative floor.
///
/// Comparing this group against `end_to_end_anchor` bounds the achievable
/// end-to-end win: whatever fraction of a full parse this composite
/// represents is the most these scanners can address.
fn bench_hot_loop_composite(c: &mut Criterion) {
    const PLANS: usize = 2_000;
    let corpus = corpus(PLANS);
    let re = RegexPatterns::default().log_line_regex;
    let cost_re = Regex::new(
        r"\(cost=(?<min>[\d.]+)\.\.(?<max>[\d.]+)\s+rows=(?<rows>\d+)\s+width=(?<width>\d+)\)",
    )
    .unwrap();

    let all = &corpus.all;
    let plan_lines = &corpus.plan_lines;
    let node_lines = &corpus.node_lines;

    let mut group = c.benchmark_group("hot_loop_composite");
    group.sample_size(20);
    group.measurement_time(Duration::from_secs(10));
    group.throughput(Throughput::Bytes(total_bytes(all)));

    group.bench_function("current", |b| {
        b.iter(|| {
            for line in all.iter() {
                black_box(split_legacy_regex(black_box(line), &re));
            }
            for line in plan_lines.iter() {
                black_box(indent_legacy_chars(black_box(line)));
            }
            for line in node_lines.iter() {
                if let Some(c) = cost_re.captures(black_box(line)) {
                    black_box((
                        c["min"].parse::<f64>().ok(),
                        c["max"].parse::<f64>().ok(),
                        c["rows"].parse::<u64>().ok(),
                        c["width"].parse::<u32>().ok(),
                    ));
                }
            }
        });
    });

    group.bench_function("optimised", |b| {
        b.iter(|| {
            for line in all.iter() {
                black_box(split_log_line(black_box(line), &re));
            }
            for line in plan_lines.iter() {
                black_box(get_indent_level(black_box(line)));
            }
            for line in node_lines.iter() {
                black_box(pg_plansight_core::simd_scan::parse_cost_tuple(
                    black_box(line).as_bytes(),
                ));
            }
        });
    });
    group.finish();
}

// ---------------------------------------------------------------------------
// 7. End-to-end anchor, so the per-primitive wins can be put in proportion.
// ---------------------------------------------------------------------------

fn bench_end_to_end_anchor(c: &mut Criterion) {
    let content = realistic_log(2_000);
    let mut group = c.benchmark_group("end_to_end_anchor");
    group.sample_size(10);
    group.measurement_time(Duration::from_secs(10));
    group.throughput(Throughput::Bytes(content.len() as u64));
    group.bench_function("parse_2k_plans", |b| {
        b.iter(|| {
            let mut parser = PostgreSQLLogParser::new();
            black_box(
                parser
                    .parse_string_with_progress(black_box(&content), |_, _| {})
                    .unwrap(),
            )
        });
    });
    group.finish();
}

criterion_group!(
    benches,
    bench_timestamp_split,
    bench_indent_level,
    bench_node_detection,
    bench_node_classification,
    bench_cost_extraction,
    bench_hot_loop_composite,
    bench_end_to_end_anchor
);
criterion_main!(benches);
