[package]
name = "pg-loganalyze-core"
version = "0.1.0"
edition = "2024"
description = "Core parsing functionality for PostgreSQL auto_explain logs"
license = "MIT"
authors = ["Ege Apak <ege@apak.dev>"]
homepage = "https://github.com/egeapak/pg-loganalyze"
repository = "https://github.com/egeapak/pg-loganalyze"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bzip2 = { workspace = true }
chrono = { workspace = true }
flate2 = { workspace = true }
hashbrown = { workspace = true }
hostname = "0.4"
once_cell = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlparser = { workspace = true }
tokio = { workspace = true }
xxhash-rust = { version = "0.8", features = ["xxh64"] }

[dev-dependencies]
criterion = { workspace = true }
tempfile = { workspace = true }

[[bench]]
name = "log_parsing"
harness = false