[package]
name = "pg-loganalyze-core"
version = "0.1.0"
edition = "2024"
description = "Core parsing functionality for PostgreSQL auto_explain logs"
license = "MIT"
authors = ["Ege Apak <ege@apak.dev>"]
homepage = "https://github.com/egeapak/pg-loganalyze"
repository = "https://github.com/egeapak/pg-loganalyze"

[dependencies]
anyhow = { workspace = true }
bzip2 = { workspace = true }
chrono = { workspace = true }
flate2 = { workspace = true }
hashbrown = { workspace = true }
hostname = "0.4"
once_cell = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlparser = { workspace = true, features = ["visitor"] }
statrs = { workspace = true }
tracing = { workspace = true }
xxhash-rust = { workspace = true }

[dev-dependencies]
approx = "0.5"
criterion = { workspace = true }
tempfile = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }

[[bench]]
name = "log_parsing"
harness = false

